//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgetHubWeb.GHServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GHServiceRef.GadgetHubService1Soap")]
    public interface GadgetHubService1Soap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        GadgetHubWeb.GHServiceRef.LoginResponse Login(GadgetHubWeb.GHServiceRef.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<GadgetHubWeb.GHServiceRef.LoginResponse> LoginAsync(GadgetHubWeb.GHServiceRef.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public GadgetHubWeb.GHServiceRef.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(GadgetHubWeb.GHServiceRef.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public GadgetHubWeb.GHServiceRef.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(GadgetHubWeb.GHServiceRef.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GadgetHubService1SoapChannel : GadgetHubWeb.GHServiceRef.GadgetHubService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GadgetHubService1SoapClient : System.ServiceModel.ClientBase<GadgetHubWeb.GHServiceRef.GadgetHubService1Soap>, GadgetHubWeb.GHServiceRef.GadgetHubService1Soap {
        
        public GadgetHubService1SoapClient() {
        }
        
        public GadgetHubService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GadgetHubService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GadgetHubService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GadgetHubService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GadgetHubWeb.GHServiceRef.LoginResponse GadgetHubWeb.GHServiceRef.GadgetHubService1Soap.Login(GadgetHubWeb.GHServiceRef.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string email, string password) {
            GadgetHubWeb.GHServiceRef.LoginRequest inValue = new GadgetHubWeb.GHServiceRef.LoginRequest();
            inValue.Body = new GadgetHubWeb.GHServiceRef.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            GadgetHubWeb.GHServiceRef.LoginResponse retVal = ((GadgetHubWeb.GHServiceRef.GadgetHubService1Soap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GadgetHubWeb.GHServiceRef.LoginResponse> GadgetHubWeb.GHServiceRef.GadgetHubService1Soap.LoginAsync(GadgetHubWeb.GHServiceRef.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<GadgetHubWeb.GHServiceRef.LoginResponse> LoginAsync(string email, string password) {
            GadgetHubWeb.GHServiceRef.LoginRequest inValue = new GadgetHubWeb.GHServiceRef.LoginRequest();
            inValue.Body = new GadgetHubWeb.GHServiceRef.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((GadgetHubWeb.GHServiceRef.GadgetHubService1Soap)(this)).LoginAsync(inValue);
        }
    }
}
